# Generated by Django 4.2.7 on 2023-11-12 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useranswer',
            name='answer',
        ),
        migrations.AddField(
            model_name='useranswer',
            name='answer_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='answer_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='answer_yes_no',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
