# Generated by Django 4.2.7 on 2023-11-12 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_rename_useranswer_answer_question_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='answer_number',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='answer_text',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='answer_yes_no',
        ),
        migrations.AddField(
            model_name='answer',
            name='answer',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
